/**
 * Product filtering logic (Task 7.5).
 *
 * Pure, side-effect-free filtering used by the category-detail page filter
 * controls (Req 5.6, 5.7, 5.8). A Visitor may narrow a Category's products by:
 *
 * - **Subcategory** — the product's `categoryId` must equal the selected
 *   subcategory id (Req 5.6 — subcategory pills).
 * - **Stores** — the product's `storeId` must be a member of the selected set
 *   of store ids (Req 5.6 — store checkboxes).
 * - **Discount tier** — `10%+`, `30%+`, or `50%+` are *minimum* thresholds: the
 *   product's `discountPercent` must be at least the selected tier (Req 5.6).
 * - **Price range** — an inclusive `[min, max]` band the product's
 *   `currentPrice` must fall within (Req 5.6 — ₹0 to ₹1,00,000 control).
 *
 * Filters combine with **AND** semantics: a product is included only when it
 * satisfies *every* active filter simultaneously (Req 5.7). Removing a filter
 * simply drops its clause and re-evaluates the remainder (Req 5.8).
 *
 * This module exposes two complementary views of the same contract:
 *
 * 1. {@link matchesFilters} — a pure predicate over a product-like object,
 *    suitable for in-memory filtering and exhaustive property testing
 *    (Property 19).
 * 2. {@link buildProductFilterQuery} — a MongoDB filter fragment expressing the
 *    identical semantics for use by the catalog data loaders. The two are kept
 *    deliberately equivalent so the predicate faithfully models the query.
 *
 * Price values share the storage unit of `Product.currentPrice` (integer
 * paise — see `lib/models/types.ts`); callers convert rupee inputs to paise
 * before building filters.
 */
/**
 * A MongoDB filter fragment over the product fields this module constrains.
 * Mirrors the relevant `Product` query shape without depending on a mongoose
 * `FilterQuery` export, which this runtime's type bundle does not provide.
 */
export interface ProductFilterQuery {
  categoryId?: string;
  storeId?: { $in: string[] };
  discountPercent?: { $gte: number };
  currentPrice?: { $gte?: number; $lte?: number };
}

/** The selectable discount thresholds, in percent (Req 5.6: 10%+, 30%+, 50%+). */
export const DISCOUNT_TIERS = [10, 30, 50] as const;

/** A minimum-discount threshold a product must meet or exceed. */
export type DiscountTier = (typeof DISCOUNT_TIERS)[number];

/** An inclusive price band; either bound may be omitted to leave it unbounded. */
export interface PriceRange {
  /** Inclusive lower bound (same unit as `currentPrice`). */
  min?: number | null;
  /** Inclusive upper bound (same unit as `currentPrice`). */
  max?: number | null;
}

/**
 * The set of filters a Visitor can apply on a Category detail page. Every field
 * is optional; an omitted, null, or empty value means that filter is inactive
 * and is not considered when matching.
 */
export interface ProductFilters {
  /** Selected subcategory id; the product's `categoryId` must equal it. */
  subcategoryId?: string | null;
  /** Selected store ids; the product's `storeId` must be one of these. */
  storeIds?: readonly string[] | null;
  /** Minimum discount threshold the product's `discountPercent` must meet. */
  discountTier?: DiscountTier | null;
  /** Inclusive price band the product's `currentPrice` must fall within. */
  priceRange?: PriceRange | null;
}

/**
 * The minimal product shape the predicate inspects. `Product` documents and the
 * public product summaries both structurally satisfy this, as do the plain
 * objects generated by property tests.
 */
export interface FilterableProduct {
  /** Owning category/subcategory id. */
  categoryId: unknown;
  /** Owning store id. */
  storeId: unknown;
  /** Current price in the same unit used by the filter's price range. */
  currentPrice: number;
  /** Derived discount percentage (1..100) or null when none applies. */
  discountPercent: number | null;
}

/** Compare two id-like values by string form so ObjectId and string ids match. */
function idEquals(a: unknown, b: unknown): boolean {
  return String(a) === String(b);
}

/** Is the subcategory filter active (a non-empty id was selected)? */
function hasSubcategory(filters: ProductFilters): filters is ProductFilters & {
  subcategoryId: string;
} {
  return typeof filters.subcategoryId === 'string' && filters.subcategoryId.length > 0;
}

/** Is the stores filter active (at least one store id was selected)? */
function hasStores(filters: ProductFilters): filters is ProductFilters & {
  storeIds: readonly string[];
} {
  return Array.isArray(filters.storeIds) && filters.storeIds.length > 0;
}

/** Is the discount-tier filter active (a tier was selected)? */
function hasDiscountTier(filters: ProductFilters): filters is ProductFilters & {
  discountTier: DiscountTier;
} {
  return typeof filters.discountTier === 'number';
}

/** The active lower bound of the price range, or null when unbounded. */
function priceMin(filters: ProductFilters): number | null {
  const min = filters.priceRange?.min;
  return typeof min === 'number' && Number.isFinite(min) ? min : null;
}

/** The active upper bound of the price range, or null when unbounded. */
function priceMax(filters: ProductFilters): number | null {
  const max = filters.priceRange?.max;
  return typeof max === 'number' && Number.isFinite(max) ? max : null;
}

/**
 * Reports whether `filters` carries at least one active clause. Useful for
 * deciding whether to show the "clear all" affordance / active-chip row.
 */
export function hasActiveFilters(filters: ProductFilters): boolean {
  return (
    hasSubcategory(filters) ||
    hasStores(filters) ||
    hasDiscountTier(filters) ||
    priceMin(filters) !== null ||
    priceMax(filters) !== null
  );
}

/**
 * Pure AND-combined predicate: returns `true` iff `product` satisfies *every*
 * active filter in `filters` (Req 5.7). A product with no active filters always
 * matches. A `null` discount never satisfies an active discount-tier filter.
 */
export function matchesFilters(
  product: FilterableProduct,
  filters: ProductFilters,
): boolean {
  // Subcategory: categoryId must equal the selected subcategory (Req 5.6).
  if (hasSubcategory(filters) && !idEquals(product.categoryId, filters.subcategoryId)) {
    return false;
  }

  // Stores: storeId must be a member of the selected set (Req 5.6).
  if (hasStores(filters)) {
    const inSelectedStore = filters.storeIds.some((id) => idEquals(product.storeId, id));
    if (!inSelectedStore) {
      return false;
    }
  }

  // Discount tier: discountPercent must meet or exceed the threshold (Req 5.6).
  if (hasDiscountTier(filters)) {
    if (product.discountPercent === null || product.discountPercent < filters.discountTier) {
      return false;
    }
  }

  // Price range: currentPrice must fall within the inclusive band (Req 5.6).
  const min = priceMin(filters);
  if (min !== null && product.currentPrice < min) {
    return false;
  }
  const max = priceMax(filters);
  if (max !== null && product.currentPrice > max) {
    return false;
  }

  return true;
}

/**
 * Filter an in-memory list of products to exactly those matching all active
 * filters (Req 5.7). Order is preserved so a sorted input stays sorted.
 */
export function applyProductFilters<T extends FilterableProduct>(
  products: readonly T[],
  filters: ProductFilters,
): T[] {
  return products.filter((product) => matchesFilters(product, filters));
}

/**
 * Build a MongoDB filter fragment expressing the same AND-combined semantics as
 * {@link matchesFilters}, for use inside the catalog data loaders. Only active
 * clauses are emitted, so an empty filter set yields an empty fragment that the
 * caller can merge with its base query (e.g. `{ status: 'active', categoryId }`).
 */
export function buildProductFilterQuery(filters: ProductFilters): ProductFilterQuery {
  const query: ProductFilterQuery = {};

  if (hasSubcategory(filters)) {
    query.categoryId = filters.subcategoryId;
  }

  if (hasStores(filters)) {
    query.storeId = { $in: [...filters.storeIds] };
  }

  if (hasDiscountTier(filters)) {
    // A null discountPercent must not match; `$gte` already excludes null.
    query.discountPercent = { $gte: filters.discountTier };
  }

  const min = priceMin(filters);
  const max = priceMax(filters);
  if (min !== null || max !== null) {
    const price: { $gte?: number; $lte?: number } = {};
    if (min !== null) price.$gte = min;
    if (max !== null) price.$lte = max;
    query.currentPrice = price;
  }

  return query;
}
